In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random


# Read the data in, can also use dtype guessing to handle the column memory demanding
# In this case, trun the low_memory = Flase to handle
train_data=pd.read_csv("data/Incidents_Responded_to_by_Fire_Companies.csv",low_memory=False)

# train_data=train_data.drop("Id",1)
train_data.head()

print('Total number of incidents: {}'.format(len(train_data)))


Total number of incidents: 2277779


In [62]:
value = np.array(train_data['INCIDENT_TYPE_DESC'])
import collections
count = collections.Counter(value)
max_count_of_incident = list(count.most_common(1))
a = max_count_of_incident[0][1]/len(train_data)
print('The most common type of incident rate is {}'.format( a ))

The most common type of incident rate is 0.3614828304238471


In [66]:
print('Ratio of 111-building fire to 651 - Smoke scare: {}'.format(count['111 - Building fire']/count['651 - Smoke scare, odor of smoke']))


Ratio of 111-building fire to 651 - Smoke scare: 0.08789046762106846


In [114]:
a = train_data.loc[(train_data["INCIDENT_TYPE_DESC"]=="710 - Malicious, mischievous false call, other") & (train_data["BOROUGH_DESC"]=="1 - Manhattan") , ["INCIDENT_TYPE_DESC","BOROUGH_DESC"]]
b = train_data.loc[(train_data["INCIDENT_TYPE_DESC"]=="710 - Malicious, mischievous false call, other") & (train_data["BOROUGH_DESC"]=="3 - Staten Island") , ["INCIDENT_TYPE_DESC","BOROUGH_DESC"]]
print(a.count()/b.count())

INCIDENT_TYPE_DESC    25240
BOROUGH_DESC          25240
dtype: int64
INCIDENT_TYPE_DESC    3.049783
BOROUGH_DESC          3.049783
dtype: float64


In [121]:
train_data['INCIDENT_DATE_TIME'] = pd.to_datetime(train_data['INCIDENT_DATE_TIME'])
#pd.DatetimeIndex(train_data['INCIDENT_DATE_TIME'])



In [124]:
train_data['ARRIVAL_DATE_TIME'] = pd.to_datetime(train_data['ARRIVAL_DATE_TIME'])



INCIDENT_TYPE_DESC   BOROUGH_DESC
52       710 - Malicious, mischievous false call, other  1 - Manhattan
68       710 - Malicious, mischievous false call, other  1 - Manhattan
92       710 - Malicious, mischievous false call, other  1 - Manhattan
101      710 - Malicious, mischievous false call, other  1 - Manhattan
102      710 - Malicious, mischievous false call, other  1 - Manhattan
131      710 - Malicious, mischievous false call, other  1 - Manhattan
163      710 - Malicious, mischievous false call, other  1 - Manhattan
168      710 - Malicious, mischievous false call, other  1 - Manhattan
171      710 - Malicious, mischievous false call, other  1 - Manhattan
174      710 - Malicious, mischievous false call, other  1 - Manhattan
184      710 - Malicious, mischievous false call, other  1 - Manhattan
196      710 - Malicious, mischievous false call, other  1 - Manhattan
197      710 - Malicious, mischievous false call, other  1 - Manhattan
216      710 - Malicious, mischievous false call, other  1 - Manhattan
232      710 - Malicious, mischievous false call, other  1 - Manhattan
282      710 - Malicious, mischievous false call, other  1 - Manhattan
293      710 - Malicious, mischievous false call, other  1 - Manhattan
300      710 - Malicious, mischievous false call, other  1 - Manhattan
310      710 - Malicious, mischievous false call, other  1 - Manhattan
320      710 - Malicious, mischievous false call, other  1 - Manhattan
342      710 - Malicious, mischievous false call, other  1 - Manhattan
455      710 - Malicious, mischievous false call, other  1 - Manhattan
655      710 - Malicious, mischievous false call, other  1 - Manhattan
688      710 - Malicious, mischievous false call, other  1 - Manhattan
737      710 - Malicious, mischievous false call, other  1 - Manhattan
743      710 - Malicious, mischievous false call, other  1 - Manhattan
751      710 - Malicious, mischievous false call, other  1 - Manhattan
1037     710 - Malicious, mischievous false call, other  1 - Manhattan
1100     710 - Malicious, mischievous false call, other  1 - Manhattan
1203     710 - Malicious, mischievous false call, other  1 - Manhattan
...                                                 ...            ...
2273408  710 - Malicious, mischievous false call, other  1 - Manhattan
2273450  710 - Malicious, mischievous false call, other  1 - Manhattan
2273840  710 - Malicious, mischievous false call, other  1 - Manhattan
2274145  710 - Malicious, mischievous false call, other  1 - Manhattan
2274237  710 - Malicious, mischievous false call, other  1 - Manhattan
2274268  710 - Malicious, mischievous false call, other  1 - Manhattan
2274383  710 - Malicious, mischievous false call, other  1 - Manhattan
2274385  710 - Malicious, mischievous false call, other  1 - Manhattan
2274404  710 - Malicious, mischievous false call, other  1 - Manhattan
2274473  710 - Malicious, mischievous false call, other  1 - Manhattan
2274488  710 - Malicious, mischievous false call, other  1 - Manhattan
2274494  710 - Malicious, mischievous false call, other  1 - Manhattan
2274503  710 - Malicious, mischievous false call, other  1 - Manhattan
2274888  710 - Malicious, mischievous false call, other  1 - Manhattan
2274893  710 - Malicious, mischievous false call, other  1 - Manhattan
2274992  710 - Malicious, mischievous false call, other  1 - Manhattan
2275404  710 - Malicious, mischievous false call, other  1 - Manhattan
2275857  710 - Malicious, mischievous false call, other  1 - Manhattan
2275926  710 - Malicious, mischievous false call, other  1 - Manhattan
2276112  710 - Malicious, mischievous false call, other  1 - Manhattan
2276145  710 - Malicious, mischievous false call, other  1 - Manhattan
2276305  710 - Malicious, mischievous false call, other  1 - Manhattan
2276549  710 - Malicious, mischievous false call, other  1 - Manhattan
2276711  710 - Malicious, mischievous false call, other  1 - Manhattan
2276886  710 - Malicious, mischievous false call, other  1 - 

In [128]:
train_data=pd.read_csv("data/Incidents_Responded_to_by_Fire_Companies.csv",low_memory=False)
Building_fire_start = train_data.loc[(train_data["INCIDENT_TYPE_DESC"]=="111 - Building fire") & (train_data["INCIDENT_DATE_TIME"]) , ["INCIDENT_TYPE_DESC","INCIDENT_DATE_TIME"]]
Building_fire_arrive = train_data.loc[(train_data["INCIDENT_TYPE_DESC"]=="111 - Building fire") & (train_data["ARRIVAL_DATE_TIME"]) , ["INCIDENT_TYPE_DESC","ARRIVAL_DATE_TIME"]]

In [130]:
Building_fire_start['INCIDENT_DATE_TIME'] = pd.to_datetime(Building_fire_start['INCIDENT_DATE_TIME'])
Building_fire_arrive['ARRIVAL_DATE_TIME'] = pd.to_datetime(Building_fire_arrive['ARRIVAL_DATE_TIME'])

In [138]:
Building_fire_arrive['Time_difference'] = Building_fire_arrive['ARRIVAL_DATE_TIME'] - Building_fire_start['INCIDENT_DATE_TIME']
Building_fire_arrive['Time_difference_second'] = Building_fire_arrive['Time_difference'].dt.total_seconds()

In [144]:
Building_fire_arrive['Time_difference_minutes'] = Building_fire_arrive['Time_difference_second'] / 60.0
print(Building_fire_arrive['Time_difference_minutes'].quantile([0.25,0.5,0.75]))


0.25    2.85
0.50    3.45
0.75    4.15
Name: Time_difference_minutes, dtype: float64


In [186]:
Cooking_fire_and_time = train_data[["INCIDENT_TYPE_DESC" , "INCIDENT_DATE_TIME"]]
Cooking_fire_and_time['INCIDENT_DATE_TIME'] = pd.to_datetime(Cooking_fire_and_time['INCIDENT_DATE_TIME']).dt.hour


C:\Users\Jie\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


INCIDENT_TYPE_DESC  INCIDENT_DATE_TIME
0                        300 - Rescue, EMS incident, other                   0
1        735A - Unwarranted alarm/defective condition o...                   0
2                        300 - Rescue, EMS incident, other                   0
3                      412 - Gas leak (natural gas or LPG)                   0
4        735A - Unwarranted alarm/defective condition o...                   0
5        735A - Unwarranted alarm/defective condition o...                   0
6         353 - Removal of victim(s) from stalled elevator                   0
7                         651 - Smoke scare, odor of smoke                   0
8                   331 - Lock-in (if lock out , use 511 )                   0
9           710 - Malicious, mischievous false call, other                   0
10                  555 - Defective elevator, no occupants                   0
11       735A - Unwarranted alarm/defective condition o...                   0
12                               522 - Water or steam leak                   0
13                       150 - Outside rubbish fire, other                   0
14                       300 - Rescue, EMS incident, other                   0
15                               522 - Water or steam leak                   0
16       735A - Unwarranted alarm/defective condition o...                   0
17                        651 - Smoke scare, odor of smoke                   0
18                  331 - Lock-in (if lock out , use 511 )                   0
19                        651 - Smoke scare, odor of smoke                   0
20              151 - Outside rubbish, trash or waste fire                   0
21                       300 - Rescue, EMS incident, other                   0
22                        651 - Smoke scare, odor of smoke                   0
23                  118 - Trash or rubbish fire, contained                   0
24              322 - Motor vehicle accident with injuries                   0
25                       300 - Rescue, EMS incident, other                   0
26              151 - Outside rubbish, trash or waste fire                   0
27                       300 - Rescue, EMS incident, other                   0
28        746 - Carbon monoxide detector activation, no CO                   0
29             142 - Brush or brush-and-grass mixture fire                   0
...                                                    ...                 ...
2277749                  300 - Rescue, EMS incident, other                  23
2277750                  300 - Rescue, EMS incident, other                  23
2277751     710 - Malicious, mischievous false call, other                  23
2277752  735A - Unwarranted alarm/defective condition o...                  23
2277753   353 - Removal of victim(s) from stalled elevator                  23
2277754                412 - Gas leak (natural gas or LPG)                  23
2277755                  300 - Rescue, EMS incident, other                  23
2277756   746 - Carbon monoxide detector activation, no CO                  23
2277757          113 - Cooking fire, confined to container                  23
2277758  735A - Unwarranted alarm/defective condition o...                  23
2277759        352 - Extrication of victim(s) from vehicle                  23
2277760                   651 - Smoke scare, odor of smoke                  23
2277761                  300 - Rescue, EMS incident, other                  23
2277762                   651 - Smoke scare, odor of smoke                  23
2277763         740B - Unnecessary alarm/other known cause                  23
2277764                          522 - Water or steam leak                  23
2277765                  300 - Rescue, EMS incident, other                  23
2277766                  300 - Rescue, EMS incident, other                  12
2277767                  300 - Rescue, EMS incident, other                  12
2277768    

In [203]:
Cooking_fire_and_time
#=="113 - Cooking fire, confined to container"
a = Cooking_fire_and_time.loc[Cooking_fire_and_time['INCIDENT_TYPE_DESC'] =="113 - Cooking fire, confined to container"]
group1 = Cooking_fire_and_time.groupby('INCIDENT_DATE_TIME', as_index=False)['INCIDENT_TYPE_DESC'].count()
group1

INCIDENT_DATE_TIME  INCIDENT_TYPE_DESC
0                    0               71631
1                    1               57394
2                    2               47079
3                    3               41313
4                    4               39658
5                    5               41848
6                    6               52133
7                    7               72671
8                    8               91402
9                    9              102894
10                  10              109463
11                  11              113931
12                  12              117203
13                  13              121908
14                  14              126016
15                  15              126410
16                  16              128304
17                  17              136283
18                  18              133853
19                  19              127787
20                  20              120731
21                  21              110342
22                  22               99051
23                  23               88474

In [216]:
group2 = a.groupby('INCIDENT_DATE_TIME', as_index=False)['INCIDENT_TYPE_DESC'].count()
group2

INCIDENT_DATE_TIME  INCIDENT_TYPE_DESC
0                    0                2047
1                    1                1571
2                    2                1203
3                    3                1059
4                    4                 951
5                    5                 998
6                    6                1455
7                    7                2007
8                    8                2818
9                    9                3503
10                  10                3983
11                  11                4464
12                  12                5000
13                  13                4963
14                  14                4979
15                  15                5150
16                  16                5680
17                  17                6541
18                  18                6806
19                  19                6456
20                  20                5451
21                  21                4284
22                  22                3140
23                  23                2530

In [219]:
group3 = group2['INCIDENT_TYPE_DESC']/group1['INCIDENT_TYPE_DESC']
print('The highest cooking fire propotion is {}'.format(group3.max()))

The highest cooking fire propotion is 0.050846824501505385


In [328]:
resident_zip_code =pd.read_csv("data/2010+Census+Population+By+Zipcode+(ZCTA).csv",low_memory=False)
resident_zip_code["Zip Code ZCTA"] = resident_zip_code["Zip Code ZCTA"].astype('float')
#resident_zip_code.head()
resident_zip_code = resident_zip_code.rename(columns={"Zip Code ZCTA": "ZIP_CODE"})
zip_incident = train_data.loc[(train_data["INCIDENT_TYPE_DESC"]=="111 - Building fire") & (train_data["ZIP_CODE"]) , ["INCIDENT_TYPE_DESC","ZIP_CODE"]]
zip_incident["ZIP_CODE"] = zip_incident["ZIP_CODE"].astype(float)

population_zip_fire = pd.merge(zip_incident,resident_zip_code,how='inner', on = ['ZIP_CODE'] )

count_fire_with_pop = population_zip_fire.groupby(population_zip_fire['2010 Census Population']).size().reset_index(name='Num. Building fire')
count_fire_with_pop['2010 Census Population']
#zip_incident
#population_zip_fire = train_data.loc[population_zip_fire["Zip Code ZCTA"] == population_zip_fire["ZIP_CODE"] & (population_zip_fire["2010 Census Population"]),["ZIP_CODE","2010 Census Population"]]
#population_zip_fire



0           0
1        1806
2        3011
3        3089
4        4079
5        4534
6        5229
7        6988
8        7135
9        7853
10      11916
11      12281
12      13393
13      13532
14      14016
15      14096
16      15293
17      16575
18      17416
19      17590
20      17823
21      17949
22      18540
23      18556
24      18884
25      19088
26      19168
27      19341
28      20300
29      20408
        ...  
142     76174
143     78134
144     78309
145     78731
146     78895
147     79132
148     79492
149     80018
150     81410
151     81677
152     84500
153     85510
154     85871
155     86408
156     86547
157     87757
158     88630
159     89830
160     90117
161     92221
162     93386
163     93877
164     94469
165     94600
166     97060
167     98592
168     99598
169    100820
170    101572
171    109931
Name: 2010 Census Population, Length: 172, dtype: int64

In [334]:
results = {}
coeffs = numpy.polyfit(count_fire_with_pop['2010 Census Population'],count_fire_with_pop['Num. Building fire'],2)
x = count_fire_with_pop['2010 Census Population']
y = count_fire_with_pop['Num. Building fire']
p = numpy.poly1d(coeffs)
# fit values, and mean
yhat = p(x)                         # or [p(z) for z in x]
ybar = numpy.sum(y)/len(y)          # or sum(y)/len(y)
ssreg = numpy.sum((yhat-ybar)**2)   # or sum([ (yihat - ybar)**2 for yihat in yhat])
sstot = numpy.sum((y - ybar)**2)    # or sum([ (yi - ybar)**2 for yi in y])
results['determination'] = ssreg / sstot
print(results['determination'])

0.5943492242479399


In [605]:
#CO_detector = CO_detector[np.isfinite(df['EPS'])]
CO_detector = train_data.loc[train_data["CO_DETECTOR_PRESENT_DESC"].isin(['Yes','No']) & train_data["CO_DETECTOR_PRESENT_DESC"]]
CO_detector = CO_detector[["CO_DETECTOR_PRESENT_DESC","INCIDENT_DATE_TIME","LAST_UNIT_CLEARED_DATE_TIME"]]
CO_detector['INCIDENT_DATE_TIME'] = pd.to_datetime(CO_detector['INCIDENT_DATE_TIME'])
CO_detector['LAST_UNIT_CLEARED_DATE_TIME'] = pd.to_datetime(CO_detector['LAST_UNIT_CLEARED_DATE_TIME'])


In [607]:
CO_detector['Time_difference'] = CO_detector['LAST_UNIT_CLEARED_DATE_TIME'] - CO_detector['INCIDENT_DATE_TIME']
CO_detector['Time_difference_minutes'] = CO_detector['Time_difference'].dt.total_seconds()/60.0


In [585]:
#time_group = CO_detector.groupby('Time_difference_minutes',np.linspace(20.0,70.0,num = 6))
#bins = [[20,30],[30,40],[40,50],[50,60],[60,70]]
bins = [20,30,40,50,60,70]
group_names = ['20-30','30-40','40-50','50-60','60-70']

CO_detector["Time_difference_minutes"] = CO_detector["Time_difference_minutes"].astype('float')
CO_detector = CO_detector.loc[CO_detector["Time_difference_minutes"]>19.9999 ]
CO_detector = CO_detector.loc[CO_detector["Time_difference_minutes"]<70.001 ]

time_group_1 = CO_detector.groupby( pd.cut(CO_detector['Time_difference_minutes'],bins,include_lowest=True) ).count()
time_group_Yes = CO_detector.loc[CO_detector["CO_DETECTOR_PRESENT_DESC"] == 'Yes' ]

time_group_Yes = time_group_Yes.groupby( pd.cut(time_group_Yes['Time_difference_minutes'],bins,include_lowest=True) ).count()
time_group_No  = CO_detector.loc[CO_detector["CO_DETECTOR_PRESENT_DESC"] == 'No']

time_group_No = time_group_No.groupby( pd.cut(time_group_No['Time_difference_minutes'],bins,include_lowest=True) ).count()
a= time_group_No['CO_DETECTOR_PRESENT_DESC']/time_group_1['CO_DETECTOR_PRESENT_DESC']

b= time_group_Yes['INCIDENT_DATE_TIME']/time_group_1['INCIDENT_DATE_TIME']
a = np.array(a)
time_group_No

CO_DETECTOR_PRESENT_DESC  INCIDENT_DATE_TIME  \
Time_difference_minutes                                                 
(19.999, 30.0]                               1181                1181   
(30.0, 40.0]                                  586                 586   
(40.0, 50.0]                                  348                 348   
(50.0, 60.0]                                  249                 249   
(60.0, 70.0]                                  158                 158   

                         LAST_UNIT_CLEARED_DATE_TIME  Time_difference  \
Time_difference_minutes                                                 
(19.999, 30.0]                                  1181             1181   
(30.0, 40.0]                                     586              586   
(40.0, 50.0]                                     348              348   
(50.0, 60.0]                                     249              249   
(60.0, 70.0]                                     158              158   

                         Time_difference_second  Time_difference_minutes  
Time_difference_minutes                                                   
(19.999, 30.0]                             1181                     1181  
(30.0, 40.0]                                586                      586  
(40.0, 50.0]                                348                      348  
(50.0, 60.0]                                249                      249  
(60.0, 70.0]                                158                      158

In [586]:
time_group_1 = time_group_1.rename(index=str,columns ={"CO_DETECTOR_PRESENT_DESC" : "count_total"})
time_group_1 = time_group_1["count_total"]
time_group_1 = np.array(time_group_1)

In [587]:
time_group_Yes  = time_group_Yes.rename(index=str,columns ={"CO_DETECTOR_PRESENT_DESC" : "count_yes"})
time_group_Yes = time_group_Yes["count_yes"]
time_group_Yes = np.array(time_group_Yes)

time_group_No  = time_group_No.rename(index=str,columns ={"CO_DETECTOR_PRESENT_DESC" : "count_no"})
time_group_No = time_group_No["count_no"]
time_group_No = np.array(time_group_No)
print(time_group_Yes,time_group_No)

[6501 2145  923  481  235] [1181  586  348  249  158]


In [588]:
number30 = CO_detector.loc[CO_detector["Time_difference_minutes"]==30.00 ]
number30 = number30['CO_DETECTOR_PRESENT_DESC'].count()
number40 = CO_detector.loc[CO_detector["Time_difference_minutes"]==40.00 ]
number40 = number40['CO_DETECTOR_PRESENT_DESC'].count()
number50 = CO_detector.loc[CO_detector["Time_difference_minutes"]==50.00 ]
number50 = number50['CO_DETECTOR_PRESENT_DESC'].count()
number60 = CO_detector.loc[CO_detector["Time_difference_minutes"]==60.00 ]
number60 = number60['CO_DETECTOR_PRESENT_DESC'].count()


In [582]:
num_add = [number30,number40,number50,number60]
print(time_group_1)

for i in range(1,len(time_group_1)-1):
    time_group_1[i] += num_add[i-1]


[7682 2731 1271  730  393]


In [589]:
number30y = CO_detector.loc[CO_detector["Time_difference_minutes"]==30.00 ]
number30y = number30y.loc[number30y["CO_DETECTOR_PRESENT_DESC"] == 'Yes' ]
number30y = number30y['CO_DETECTOR_PRESENT_DESC'].count()

number40y = CO_detector.loc[CO_detector["Time_difference_minutes"]==40.00 ]
number40y = number40y.loc[number40y["CO_DETECTOR_PRESENT_DESC"] == 'Yes' ]
number40y = number40y['CO_DETECTOR_PRESENT_DESC'].count()

print(time_group_1)
time_group_Yes[1] += number30y
time_group_No[1] += num_add[0]-number30y

time_group_Yes[2] += number40y
time_group_No[2] += num_add[1]-number40y
print(time_group_Yes,time_group_No)

[7682 2731 1271  730  393]
[6501 2155  926  481  235] [1181  586  350  249  158]


In [592]:
ratio_yes = time_group_Yes/time_group_1
ratio_no  = time_group_No/time_group_1
print(ratio_yes,ratio_no)

[0.84626399 0.78908825 0.72856019 0.65890411 0.59796438] [0.15373601 0.21457342 0.27537372 0.34109589 0.40203562]


In [594]:
ratio = ratio_no/ratio_yes
print(ratio)

[0.18166436 0.27192575 0.37796976 0.51767152 0.67234043]


In [595]:
mid_point_bins = [25,35,45,55,65]
print(mid_point_bins)

[25, 35, 45, 55, 65]


In [597]:
p1 = numpy.polyfit (mid_point_bins,ratio,1)
result = numpy.polyval(p1,39)
print(result)

0.3306884900414385


In [602]:
#Question 6
from scipy import stats
print(time_group_1)
CO_detector = CO_detector.loc[CO_detector["Time_difference_minutes"]>60.0 ]
CO_detector

[7682 2731 1271  730  393]


Empty DataFrame
Columns: [CO_DETECTOR_PRESENT_DESC, INCIDENT_DATE_TIME, LAST_UNIT_CLEARED_DATE_TIME, Time_difference, Time_difference_second, Time_difference_minutes]
Index: []

In [619]:
CO_detector_NO = train_data.loc[train_data["CO_DETECTOR_PRESENT_DESC"].isin(['No']) & train_data["CO_DETECTOR_PRESENT_DESC"]]
CO_detector_NO = CO_detector_NO[["CO_DETECTOR_PRESENT_DESC","INCIDENT_DATE_TIME","LAST_UNIT_CLEARED_DATE_TIME"]]
CO_detector_NO['INCIDENT_DATE_TIME'] = pd.to_datetime(CO_detector_NO['INCIDENT_DATE_TIME'])
CO_detector_NO['LAST_UNIT_CLEARED_DATE_TIME'] = pd.to_datetime(CO_detector_NO['LAST_UNIT_CLEARED_DATE_TIME'])
CO_detector_NO['Time_difference'] = CO_detector_NO['LAST_UNIT_CLEARED_DATE_TIME'] - CO_detector_NO['INCIDENT_DATE_TIME']
CO_detector_NO['Time_difference_minutes'] = CO_detector_NO['Time_difference'].dt.total_seconds()/60.0



CO_DETECTOR_PRESENT_DESC       4785
INCIDENT_DATE_TIME             4785
LAST_UNIT_CLEARED_DATE_TIME    4785
Time_difference                4785
Time_difference_minutes        4785
dtype: int64

In [623]:
small_than60 = CO_detector_NO.loc[CO_detector_NO["Time_difference_minutes"]<=60 ]
count_small60 = small_than60['CO_DETECTOR_PRESENT_DESC'].count()


print(count_small60)

4785 158


In [629]:
over_than60 = CO_detector_NO.loc[CO_detector_NO["Time_difference_minutes"]>60 ]
over_small60 = over_than60['CO_DETECTOR_PRESENT_DESC'].count()
print(over_small60)

859


In [641]:
total = count_small60+ over_small60
pro1 = count_small60/total
pro2 = over_small60/total
print(pro1,pro2)

0.8478029766123317 0.15219702338766833


In [642]:
from scipy.stats import chisquare
chisq, p = chisquare([pro1,pro2],ddof=1)
print(chisq)

0.4838676421615926


CO_DETECTOR_PRESENT_DESC  INCIDENT_DATE_TIME  \
5377                          No 2013-01-05 21:15:33   
6005                          No 2013-01-06 14:31:43   
9014                          No 2013-01-09 09:59:52   
9114                          No 2013-01-09 11:57:05   
20856                         No 2013-01-20 15:02:04   
24919                         No 2013-01-24 09:36:42   
26482                         No 2013-01-25 12:55:44   
32608                         No 2013-01-29 23:10:34   
32841                         No 2013-01-30 08:23:48   
33214                         No 2013-01-30 14:12:59   
33414                         No 2013-01-30 17:10:30   
33578                         No 2013-01-30 19:35:07   
35412                         No 2013-02-01 07:09:32   
40898                         No 2013-02-06 09:38:35   
44860                         No 2013-02-09 20:43:40   
46548                         No 2013-02-11 07:38:26   
49478                         No 2013-02-13 14:45:56   
51554                         No 2013-02-15 15:11:26   
51668                         No 2013-02-15 17:11:10   
52370                         No 2013-02-16 09:50:00   
59127                         No 2013-02-22 20:09:51   
59822                         No 2013-02-23 13:56:38   
63154                         No 2013-02-26 20:36:44   
63607                         No 2013-02-27 08:40:02   
71294                         No 2013-03-06 13:54:36   
71520                         No 2013-03-06 17:38:21   
77244                         No 2013-03-12 11:37:21   
77480                         No 2013-03-12 15:15:34   
79505                         No 2013-03-14 14:43:08   
80375                         No 2013-03-15 11:35:43   
...                          ...                 ...   
2181781                       No 2017-10-19 17:27:19   
2182003                       No 2017-10-19 20:22:47   
2195280                       No 2017-10-29 20:31:28   
2206031                       No 2017-11-06 18:09:44   
2210404                       No 2017-11-10 07:25:56   
2211009                       No 2017-11-10 15:42:09   
2213337                       No 2017-11-12 08:52:08   
2216111                       No 2017-11-14 13:56:02   
2216645                       No 2017-11-14 21:53:35   
2217022                       No 2017-11-15 09:19:55   
2218648                       No 2017-11-16 14:52:11   
2218671                       No 2017-11-16 15:15:55   
2222151                       No 2017-11-19 09:37:08   
2222405                       No 2017-11-19 13:09:23   
2222453                       No 2017-11-19 13:52:08   
2223857                       No 2017-11-20 17:00:59   
2230300                       No 2017-11-25 17:22:03   
2232101                       No 2017-11-27 10:02:16   
2234346                       No 2017-11-29 03:57:43   
2238114                       No 2017-12-02 02:16:21   
2238288                       No 2017-12-02 08:40:07   
2249432                       No 2017-12-11 09:22:09   
2256318                       No 2017-12-16 10:26:36   
2257854                       No 2017-12-17 10:15:35   
2257960                       No 2017-12-17 11:49:58   
2268287                       No 2017-12-25 00:46:23   
2268749                       No 2017-12-25 11:43:59   
2268781                       No 2017-12-25 12:12:24   
2268793                       No 2017-12-25 12:22:43   
2269303                       No 2017-12-25 19:55:17   

        LAST_UNIT_CLEARED_DATE_TIME Time_difference  Time_difference_minutes  
5377            2013-01-05 22:43:47        01:28:14                88.233333  
6005            2013-01-06 18:27:47        03:56:04               236.066667  
9014            2013-01-09 11:26:51        01:26:59                86.983333  
9114            2013-01-09 14:53:47        02:56:42               176.700000  
20856           2013-01-20 16:48:24        01:46:20               106.333333  
24919           2013-01-24 11:08:25        01:31:43          